version: '3.8'

services:
  ollama_service:
    image: ollama/ollama:latest
    container_name: agritech_ollama
    ports:
      - "11434:11434"
    volumes:
      - E:/ollama_models:/root/.ollama
    restart: always

  agritech_ai:
    build: .
    container_name: agritech_ai_backend
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=http://ollama_service:11434
    volumes:
      - ./chroma_db:/app/chroma_db
    depends_on:
      - ollama_service
    restart: always